const typography = {
  fonts: {
    heading: 'Architects Daughter',
    body: 'Architects Daughter',
  },
  fontSizes: {
    xs: '7px',
    sm: '10px',
    md: 'var(--allec--ts--content-fs)',
    lg: 'var(--allec--ts--h6-fs)',
    xl: 'var(--allec--ts--h5-fs)',
    '2xl': 'var(--allec--ts--h4-fs)',
    '3xl': 'var(--allec--ts--h3-fs)',
    '4xl': 'var(--allec--ts--h2-fs)',
    '5xl': 'var(--allec--ts--h1-fs)',
  },
  fontWeights: {
    light: 300,
    normal: 400,
    medium: 500,
    bold: 700,
  },
  lineHeights: {
    normal: 'var(--allec--ts--content-lh)',
    none: '1',
    shorter: '1.25',
    short: '1.375',
    base: '1.5',
    tall: '1.625',
    taller: '2',
    xs: '7px',
    sm: '10px',
    md: 'var(--allec--ts--content-lh)',
    lg: 'var(--allec--ts--h6-lh)',
    xl: 'var(--allec--ts--h5-lh)',
    '2xl': 'var(--allec--ts--h4-lh)',
    '3xl': 'var(--allec--ts--h3-lh)',
    '4xl': 'var(--allec--ts--h2-lh)',
    '5xl': 'var(--allec--ts--h1-lh)',
  },
  letterSpacings: {
    tighter: '-0.05em',
    tight: '-0.025em',
    normal: '0',
    wide: '0.025em',
    wider: '0.05em',
    widest: '0.1em',
  },
}

export default typography
