import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fishy Start</title>
        <meta name="description" content="Generated by The Fish..." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="fish">
          <Image src="/fish.svg" alt="Fishy Fish" width={300} height={300} />
        </div>
      </main>
      <style jsx>{`
        main {
          height: 75vh;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .fish {
          transition: transform 1.5s ease-in-out;
        }
        .fish:hover {
          transform: rotate(360deg);
        }
      `}</style>
    </>
  )
}

export default Home
