import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fishy Start</title>
        <meta name="description" content="Generated by The Fish..." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="water">
          <div className="fish">
            <Image
              src="/hooly-herrings-black.svg"
              alt="Fishy Fish"
              width={100}
              height={75}
            />
          </div>
        </div>
      </main>
      <style jsx>{`
        .water {
          height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .fish {
          transition: all 1s ease-in-out;
        }
        .fish:hover {
          transform: rotate(360deg) scale(4);
        }
      `}</style>
    </>
  )
}

export default Home
